name: test.yml
on:
    push:
    pull_request:

permissions: {}

jobs:
    find-configs:
        name: ğŸ“‡ Find configs
        uses: ./.github/workflows/find-configs.yml

    test-source:
        runs-on: ubuntu-latest
        name: ğŸ§ªğŸ“– Test source
        needs:
            - find-configs
        strategy:
            matrix:
                config: ${{ fromJson(needs.find-configs.outputs.configs) }}
            fail-fast: false
        permissions:
            contents: read
            # pull-requests: write
        steps:
            - name: ğŸ“¥ checkout
              uses: actions/checkout@v5

            - name: ğŸ›ï¸ setup
              uses: ./.github/actions/setup

            - name: ğŸ§ªğŸ“– run tests (source)
              run: yarn test:src ${{ matrix.config }}

            - name: ğŸ§¾ report coverage
              if: always()
              uses: davelosert/vitest-coverage-report-action@v2
              with:
                  comment-on: none

    test-userscript:
        runs-on: ubuntu-latest
        name: ğŸ§ªğŸ’ Test userscript
        needs:
            - find-configs
        strategy:
            matrix:
                config: ${{ fromJson(needs.find-configs.outputs.configs) }}
            fail-fast: false
        permissions:
            contents: read
            pull-requests: write
        steps:
            - name: ğŸ“¥ checkout
              uses: actions/checkout@v5

            - name: ğŸ—ï¸ build userscript
              uses: ./.github/actions/build
              with:
                  config: ${{ matrix.config }}

            - name: ğŸ§ªğŸ’ run tests (userscript)
              run: yarn test:userscript ${{ matrix.config }}
